-- GoodMotoway: products table + storage bucket
-- Run this once in the Supabase Dashboard -> SQL Editor -> New query -> Run

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  key text,
  name text not null,
  tag text,
  price numeric not null default 0,
  description text,
  battery text,
  motor numeric,
  speed numeric,
  range_min numeric,
  range_max numeric,
  weight numeric,
  brakes text,
  tyres text,
  dims text,
  charge text,
  in_stock boolean not null default true,
  img text,
  images text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Public read access (site visitors browsing products)
create policy "Public read access" on public.products
  for select using (true);

-- Open write access (admin gate is enforced client-side only, by choice)
create policy "Public insert access" on public.products
  for insert with check (true);

create policy "Public update access" on public.products
  for update using (true) with check (true);

create policy "Public delete access" on public.products
  for delete using (true);

-- Storage bucket for product images
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

create policy "Public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

create policy "Public upload product images" on storage.objects
  for insert with check (bucket_id = 'product-images');

create policy "Public delete product images" on storage.objects
  for delete using (bucket_id = 'product-images');
