-- GoodMotoway: products table + storage bucket
-- Run this once in the Supabase Dashboard -> SQL Editor -> New query -> Run

drop table if exists public.products cascade;

create table public.products (
  id bigint generated by default as identity primary key,
  key text,
  name text not null,
  tag text,
  price numeric not null default 0,
  description text,
  battery text,
  motor numeric,
  speed numeric,
  range_min numeric,
  range_max numeric,
  weight numeric,
  brakes text,
  tyres text,
  dims text,
  charge text,
  in_stock boolean not null default true,
  img text,
  images text[] not null default '{}',
  colors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_products_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_products_updated_at();

alter table public.products enable row level security;

-- Public read access (site visitors browsing products)
create policy "Public read access" on public.products
  for select using (true);

-- Writes are restricted to the admin account (Google sign-in gate in
-- admin.html). Change the email below if the admin account changes.
create policy "Admin insert access" on public.products
  for insert with check (lower(auth.jwt() ->> 'email') = 'lazarepataraia910@gmail.com');

create policy "Admin update access" on public.products
  for update using (lower(auth.jwt() ->> 'email') = 'lazarepataraia910@gmail.com')
  with check (lower(auth.jwt() ->> 'email') = 'lazarepataraia910@gmail.com');

create policy "Admin delete access" on public.products
  for delete using (lower(auth.jwt() ->> 'email') = 'lazarepataraia910@gmail.com');

-- Storage bucket for product images
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "Public read product images" on storage.objects;
drop policy if exists "Public upload product images" on storage.objects;
drop policy if exists "Public delete product images" on storage.objects;

create policy "Public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

create policy "Admin upload product images" on storage.objects
  for insert with check (
    bucket_id = 'product-images'
    and lower(auth.jwt() ->> 'email') = 'lazarepataraia910@gmail.com'
  );

create policy "Admin delete product images" on storage.objects
  for delete using (
    bucket_id = 'product-images'
    and lower(auth.jwt() ->> 'email') = 'lazarepataraia910@gmail.com'
  );
